# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-01 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('srcpkg', models.TextField(blank=True)),
                ('hash', models.TextField(verbose_name='commit')),
                ('user', models.TextField()),
                ('status', models.TextField(blank=True, null=True)),
                ('log', models.TextField(blank=True, null=True)),
                ('start_timestamp', django_unixdatetimefield.fields.UnixDateTimeField(blank=True, null=True)),
                ('end_timestamp', django_unixdatetimefield.fields.UnixDateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jobs',
                'managed': False,
            },
        ),
    ]
